# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mincoin.ui'
#
# Created: Tue Jun 24 00:07:28 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_123 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_123.sizePolicy().hasHeightForWidth())
        self.label_123.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_123.setFont(font)
        self.label_123.setObjectName("label_123")
        self.horizontalLayout.addWidget(self.label_123)
        self.balance = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balance.sizePolicy().hasHeightForWidth())
        self.balance.setSizePolicy(sizePolicy)
        self.balance.setObjectName("balance")
        self.horizontalLayout.addWidget(self.balance)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.blockheight = QtWidgets.QLabel(self.centralwidget)
        self.blockheight.setText("")
        self.blockheight.setObjectName("blockheight")
        self.horizontalLayout.addWidget(self.blockheight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.recipient = QtWidgets.QLineEdit(self.tab_3)
        self.recipient.setObjectName("recipient")
        self.gridLayout_2.addWidget(self.recipient, 0, 1, 1, 1)
        self.send_amount = QtWidgets.QLineEdit(self.tab_3)
        self.send_amount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.send_amount.setObjectName("send_amount")
        self.gridLayout_2.addWidget(self.send_amount, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.send = QtWidgets.QPushButton(self.tab_3)
        self.send.setObjectName("send")
        self.horizontalLayout_5.addWidget(self.send)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.transactions_2 = QtWidgets.QTableView(self.tab_3)
        self.transactions_2.setObjectName("transactions_2")
        self.transactions_2.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.transactions_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.receive_amount = QtWidgets.QLineEdit(self.tab)
        self.receive_amount.setEnabled(False)
        self.receive_amount.setText("")
        self.receive_amount.setObjectName("receive_amount")
        self.gridLayout_3.addWidget(self.receive_amount, 1, 1, 1, 1)
        self.label = QtWidgets.QLineEdit(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.generate_payment_request = QtWidgets.QPushButton(self.tab)
        self.generate_payment_request.setObjectName("generate_payment_request")
        self.horizontalLayout_2.addWidget(self.generate_payment_request)
        self.address = QtWidgets.QLineEdit(self.tab)
        self.address.setObjectName("address")
        self.horizontalLayout_2.addWidget(self.address)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.transactions = QtWidgets.QTableView(self.tab)
        self.transactions.setObjectName("transactions")
        self.transactions.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.transactions)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_6)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.debug = QtWidgets.QPlainTextEdit(self.tab_6)
        self.debug.setEnabled(True)
        self.debug.setReadOnly(True)
        self.debug.setObjectName("debug")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.debug)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mincoin"))
        self.label_123.setText(_translate("MainWindow", "Balance:"))
        self.balance.setText(_translate("MainWindow", "12341234.12341234"))
        self.label_17.setText(_translate("MainWindow", "XMC"))
        self.label_2.setText(_translate("MainWindow", "Current Block Height:"))
        self.label_19.setText(_translate("MainWindow", "Recipient"))
        self.label_20.setText(_translate("MainWindow", "Amount"))
        self.label_21.setText(_translate("MainWindow", "XMC"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.label_26.setText(_translate("MainWindow", "Transactions:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Send"))
        self.label_4.setText(_translate("MainWindow", "Amount"))
        self.receive_amount.setPlaceholderText(_translate("MainWindow", "Available in a future version"))
        self.label.setPlaceholderText(_translate("MainWindow", "Optional"))
        self.label_18.setText(_translate("MainWindow", "XMC"))
        self.label_3.setText(_translate("MainWindow", "Label"))
        self.generate_payment_request.setText(_translate("MainWindow", "Generate Address"))
        self.address.setPlaceholderText(_translate("MainWindow", "Generated address will appear here."))
        self.label_25.setText(_translate("MainWindow", "Transactions:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Receive"))
        self.label_22.setText(_translate("MainWindow", "Version:"))
        self.label_15.setText(_translate("MainWindow", "mincoin-qt 0.0.1"))
        self.label_23.setText(_translate("MainWindow", "Debug"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "About"))

